# Generated by Django 4.2.2 on 2023-06-13 00:19

from django.db import migrations, models
import django.db.models.deletion
import imagens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensHistorico',
            fields=[
                ('id_imagem_historico', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=imagens.models.imagens_historico)),
                ('id_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='historico.historicos')),
            ],
        ),
    ]
